// <auto-generated />
using AspNetCoreApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspNetCoreApi.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("AspNetCoreApi.Models.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .HasColumnType("TEXT");

                    b.HasKey("PersonId");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            PersonId = 1001,
                            Age = 47,
                            Name = "Alessio",
                            SerialNumber = "1",
                            Surname = "Saltarin"
                        },
                        new
                        {
                            PersonId = 1002,
                            Age = 27,
                            Name = "Elena",
                            SerialNumber = "2",
                            Surname = "Zambrelli"
                        },
                        new
                        {
                            PersonId = 1003,
                            Age = 43,
                            Name = "Giovanni",
                            SerialNumber = "3",
                            Surname = "Rossi"
                        },
                        new
                        {
                            PersonId = 1004,
                            Age = 21,
                            Name = "Mauro",
                            SerialNumber = "4",
                            Surname = "Sangiovanni"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
